sonar.organization=pickdate
sonar.projectName=pickdate-api
sonar.projectKey=pickdate_pickdate-api
sonar.java.binaries=build/classes/java/main
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
sonar.exclusions=**/workflows/**,**/test/**,src/main/resources/**,**/*Request.java,**/*Response.java,**/*Event.java,**/*Logger.java,**/*Config.java,**/*Const.java,**/*Entity.java
sonar.cpd.exclusions=**/*Request.java,**/*Response.java,**/*Event.java,**/*Logger.java,**/*Config.java,**/*Const.java,**/*Entity.java,**/*Repository.java,**/*Config*.java
sonar.coverage.exclusions=**/*Request.java,**/*Response.java,**/*Event.java,**/*Logger.java,\
  **/*Config.java,**/*Const.java,**/*Entity.java,**/*Repository.java,**/*Config*.java,**/*Advice.java,\
  **/*Exception.java,**/*Error.java,**/*Converter.java,**/*Data.java,**/*Resolver.java,**/*Controller.java, \
  **/*Specifications.java,**/*Maybe.java
